[build]
  command = "CI= npm run build --legacy-peer-deps"
  publish = "build"
  node_version = "18.18.0"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

# Active automatiquement Netlify Forms
[[plugins]]
  package = "@netlify/plugin-gatsby" # Ignore le warning si pas Gatsby

# Redirections React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-form-handler"

[forms]
  [[forms.contact]]
    notifications = ["LartDuWeb@proton.me"]